# Generated by Django 5.2.6 on 2025-10-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faculty_id',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'HOD')], default='FACULTY', max_length=10),
        ),
    ]
