# Generated by Django 5.2.6 on 2025-11-30 10:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0027_syllabus_cie_marks_data_syllabus_reference_books'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('course_category', models.CharField(max_length=100)),
                ('teaching_hours_L', models.IntegerField(default=0)),
                ('teaching_hours_T', models.IntegerField(default=0)),
                ('teaching_hours_P', models.IntegerField(default=0)),
                ('credits', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('cie_marks', models.IntegerField(default=50)),
                ('see_marks', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=20)),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('object_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hod/activity_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('learning_objectives', models.TextField(blank=True, null=True)),
                ('course_outcomes', models.TextField(blank=True, null=True)),
                ('modules', models.TextField(blank=True, null=True)),
                ('cie_details', models.TextField(blank=True, null=True)),
                ('see_details', models.TextField(blank=True, null=True)),
                ('textbooks', models.TextField(blank=True, null=True)),
                ('reference_books', models.TextField(blank=True, null=True)),
                ('online_resources', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('course_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='hod.courseallocation')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.courseallocation')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hod.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultySyllabusPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(blank=True, max_length=6, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='faculty/syllabi/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_faculty_pdfs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_generated_pdfs', to='academics.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.collegelevelcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_generated_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HODAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='academics.branch')),
                ('hod_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HOD Assignment',
                'verbose_name_plural': 'HOD Assignments',
            },
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='hod_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='hod.hodassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('hod_assignment', 'course_code')},
        ),
        migrations.CreateModel(
            name='SchemeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.collegelevelcourse')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.scheme')),
            ],
            options={
                'unique_together': {('course_code', 'semester', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('title', models.CharField(default='Scheme PDF', max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hod/schemes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('branch', 'year', 'semester', 'created_at')},
            },
        ),
    ]
