# Generated by Django 5.2.6 on 2025-11-16 12:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0019_remove_scheme_created_by_remove_subject_scheme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('course_category', models.CharField(max_length=100)),
                ('teaching_hours_L', models.IntegerField(default=0)),
                ('teaching_hours_T', models.IntegerField(default=0)),
                ('teaching_hours_P', models.IntegerField(default=0)),
                ('credits', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('cie_marks', models.IntegerField(default=50)),
                ('see_marks', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CourseScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisites', models.TextField(blank=True, help_text='Pre-requisite knowledge', null=True)),
                ('learning_objectives', models.TextField(blank=True, help_text='What students will learn', null=True)),
                ('course_outcomes', models.TextField(blank=True, help_text='Course outcomes (CO1, CO2, etc.)', null=True)),
                ('modules', models.TextField(blank=True, help_text='Module-wise breakdown', null=True)),
                ('cie_details', models.TextField(blank=True, help_text='CIE evaluation scheme', null=True)),
                ('see_details', models.TextField(blank=True, help_text='SEE evaluation scheme', null=True)),
                ('textbooks', models.TextField(blank=True, help_text='Recommended textbooks', null=True)),
                ('reference_books', models.TextField(blank=True, help_text='Reference books', null=True)),
                ('online_resources', models.TextField(blank=True, help_text='Online resources / MOOCs', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('course_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='hod.courseallocation')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='HODAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='academics.branch')),
                ('hod_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HOD Assignment',
                'verbose_name_plural': 'HOD Assignments',
            },
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='hod_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to='hod.hodassignment'),
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Instructor', 'Instructor (Lecture)'), ('Tutorial', 'Tutorial Conductor'), ('Practical', 'Practical Coordinator'), ('Lab', 'Lab In-charge')], default='Instructor', max_length=50)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='hod.courseallocation')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='hod.faculty')),
            ],
            options={
                'ordering': ['course_allocation', 'role'],
                'unique_together': {('course_allocation', 'faculty', 'role')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('hod_assignment', 'course_code')},
        ),
    ]
