# Generated by Django 5.2.6 on 2025-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('l', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
                ('cie', models.IntegerField(default=0)),
                ('see', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('credits', models.FloatField(default=0)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=20)),
                ('is_elective', models.BooleanField(default=False)),
            ],
        ),
    ]
