# Generated by Django 5.2.6 on 2025-11-20 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_syllabus_options_and_more'),
        ('hod', '0002_schemecourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schemecourse',
            unique_together={('course_code', 'semester', 'faculty')},
        ),
        migrations.AddField(
            model_name='schemecourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.collegelevelcourse'),
        ),
        migrations.AddField(
            model_name='schemecourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemecourse',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.scheme'),
        ),
        migrations.AddField(
            model_name='schemecourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='cie_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='course_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='learning_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='modules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='online_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='reference_books',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='see_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursescheme',
            name='textbooks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemecourse',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schemecourse',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='category',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='cie',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='l',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='p',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='see',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='t',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='schemecourse',
            name='year',
        ),
    ]
