# Generated by Django 5.2.6 on 2025-11-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_alter_schemecourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='facultyassignment',
            options={},
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='facultyassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='specialization',
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyassignment',
            name='course_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.courseallocation'),
        ),
        migrations.AlterField(
            model_name='facultyassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hod.faculty'),
        ),
        migrations.RemoveField(
            model_name='facultyassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='facultyassignment',
            name='updated_on',
        ),
    ]
