# Generated by Django 5.2.6 on 2025-11-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_alter_faculty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('DOWNLOAD', 'Downloaded'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=20)),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('object_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
