# Generated by Django 5.2.6 on 2025-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='hod/activity_pdfs/'),
        ),
    ]
