# Generated by Django 5.2.6 on 2025-11-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0007_schemedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemedocument',
            name='notes',
        ),
        migrations.AddField(
            model_name='schemedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemedocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schemedocument',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
