# Generated by Django 5.2.6 on 2025-11-08 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_scheme_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='labexperiment',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='module',
            name='syllabus',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_schemes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_submitted_syllabi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='LabExperiment',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
