# Generated by Django 5.2.6 on 2025-11-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hod.faculty',),
        ),
    ]
