# Generated by Django 5.2.6 on 2025-10-13 16:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='total_credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GlobalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=255)),
                ('teaching_hours_L', models.PositiveIntegerField(default=0)),
                ('teaching_hours_T', models.PositiveIntegerField(default=0)),
                ('teaching_hours_P', models.PositiveIntegerField(default=0)),
                ('cie_marks', models.PositiveIntegerField(default=50)),
                ('see_marks', models.PositiveIntegerField(default=50)),
                ('credits', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('optional_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=120)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('total_credits', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'unique_together': {('branch', 'academic_year', 'semester')},
            },
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
