# Generated by Django 5.2.6 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_scheme_created_at_scheme_total_credits_globalcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
