# Generated by Django 5.2.6 on 2025-10-23 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_scheme_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcourse',
            name='department',
            field=models.CharField(default='All Branches', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
