# Generated by Django 5.2.6 on 2025-10-24 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_assigned_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GlobalCourse',
            new_name='CollegeLevelCourse',
        ),
        migrations.RenameField(
            model_name='semestercredit',
            old_name='total_credits',
            new_name='credits',
        ),
        migrations.RemoveField(
            model_name='semestercredit',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='semestercredit',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='semestercredit',
            name='academic_year',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='semestercredit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_credits', to='academics.branch'),
        ),
    ]
