# Generated by Django 5.2.6 on 2025-10-25 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_branch_rename_globalcourse_collegelevelcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelevelcourse',
            name='syllabus_pdf',
            field=models.FileField(blank=True, null=True, upload_to='college_courses_pdfs/'),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
