# Generated by Django 5.2.6 on 2025-10-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_collegelevelcourse_syllabus_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelevelcourse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.branch'),
        ),
        migrations.AddField(
            model_name='collegelevelcourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='cie_marks',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='course_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='credits',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='optional_branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='see_marks',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='syllabus_pdf',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_pdfs/'),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='teaching_hours_L',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='teaching_hours_P',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='teaching_hours_T',
            field=models.IntegerField(default=0),
        ),
    ]
