# Generated by Django 5.2.6 on 2025-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_collegelevelcourse_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelevelcourse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
