# Generated by Django 5.2.6 on 2025-10-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_collegelevelcourse_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercredit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_pdfs/'),
        ),
    ]
