# Generated by Django 5.2.6 on 2025-11-07 17:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_semestercredit_is_deleted_semestercredit_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegelevelcourse',
            options={'ordering': ['course_code', 'course_title']},
        ),
        migrations.AlterModelOptions(
            name='semestercredit',
            options={'ordering': ['branch__code', 'admission_year', 'semester']},
        ),
        migrations.RenameField(
            model_name='semestercredit',
            old_name='academic_year',
            new_name='admission_year',
        ),
        migrations.AddField(
            model_name='collegelevelcourse',
            name='syllabus_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='department',
            field=models.CharField(default='All Branches', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='semestercredit',
            unique_together={('branch', 'admission_year', 'semester')},
        ),
    ]
