# Generated by Django 5.2.6 on 2025-11-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_collegelevelcourse_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelevelcourse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
