# Generated by Django 5.2.6 on 2025-11-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_collegelevelcourse_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestercredit',
            options={},
        ),
        migrations.RenameField(
            model_name='semestercredit',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='semestercredit',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.AlterUniqueTogether(
            name='semestercredit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem7',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='sem8',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestercredit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='semestercredit',
            name='admission_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='semestercredit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.branch'),
        ),
        migrations.RemoveField(
            model_name='semestercredit',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='semestercredit',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='semestercredit',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='semestercredit',
            name='semester',
        ),
    ]
