# Generated by Django 5.2.6 on 2025-11-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_alter_semestercredit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='assigned_faculty',
        ),
        migrations.RemoveField(
            model_name='collegelevelcourse',
            name='syllabus_text',
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FacultyAssignment',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
