# Generated by Django 5.2.6 on 2025-11-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
