# Generated by Django 5.2.6 on 2025-11-19 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_scheme_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={},
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='pdf_file',
        ),
        migrations.CreateModel(
            name='SyllabusSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_submissions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.collegelevelcourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_submissions', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='academics.syllabus')),
            ],
            options={
                'unique_together': {('course', 'faculty')},
            },
        ),
    ]
