# Generated by Django 5.2.6 on 2025-11-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_syllabus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
