# Generated by Django 5.2.6 on 2025-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_syllabus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelevelcourse',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
