# Generated by Django 5.2.6 on 2025-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_collegelevelcourse_semester'),  # ✅ CORRECTED
    ]

    operations = [
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collegelevelcourse',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Semester number (1-8). Optional.', null=True),
        ),
    ]
