# Generated by Django 5.2.5 on 2025-11-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_alter_collegelevelcourse_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='cie_marks_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='reference_books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
