# Generated by Django 5.2.5 on 2025-12-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_syllabus_cie_marks_data_syllabus_reference_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='outcomes_po_mapping',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='outcomes_pso_mapping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
