# Generated by Django 5.2.5 on 2025-12-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_syllabus_outcomes_po_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='modules_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
