# Generated by Django 5.2.5 on 2025-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_syllabus_modules_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='modules_topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
