# Generated by Django 5.2.5 on 2025-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_syllabus_modules_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='books_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='reference_books_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
