# Generated by Django 5.2.5 on 2025-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_syllabus_books_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='co_matrix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
