# Generated by hand: add admission_year to CollegeLevelCourse
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_syllabus_co_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegelevelcourse',
            name='admission_year',
            field=models.CharField(max_length=8, null=True, blank=True, help_text='Admission year (e.g. 2025). Optional.'),
        ),
    ]
